CREATE DATABASE IF NOT EXISTS akihabarra CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE USER 'akihabarabot'@'localhost' IDENTIFIED BY 'dev';
GRANT ALL PRIVILEGES ON akihabarra.* TO 'akihabarabot'@'localhost';
FLUSH PRIVILEGES;

USE akihabarra;

CREATE TABLE users (
    id BIGINT UNSIGNED NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    balance DECIMAL(5,2) SIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (id)
);

CREATE TABLE articles (
    id INT NOT NULL AUTO_INCREMENT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(5,2) UNSIGNED NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE sales (
    id INT NOT NULL AUTO_INCREMENT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user BIGINT UNSIGNED NOT NULL,
    article INT NOT NULL,
    price DECIMAL(5,2) UNSIGNED NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE sales ADD CONSTRAINT sales_fk0 FOREIGN KEY (article) REFERENCES articles(id);
ALTER TABLE sales ADD CONSTRAINT sales_fk1 FOREIGN KEY (user) REFERENCES users(id);
